language: python
python:
  - "3.5"
# command to install dependencies
install: 
- pip install -r requirements.txt
- pip install coveralls
# command to run tests
services:
  - postgresql
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
script:
  coverage run manage.py test
after_success:
  coveralls
